version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:

  build:
    commands:
      - mvn clean test -Dcucumber.options="--tags '@TC_01'" -DExecutionPlatform="AWS_FARGATE"

  post_build:
    commands:
      - aws s3 cp . s3://853487-qualitytech/fargate/ --recursive --exclude "*" --include "*.html"
